export interface Airport {
  code: string;
  name: string;
  city: string;
}

export interface Airline {
  code: string;
  name: string;
}

export const AIRPORTS: Airport[] = [
  { code: 'JFK', name: 'John F. Kennedy International Airport', city: 'New York' },
  { code: 'LAX', name: 'Los Angeles International Airport', city: 'Los Angeles' },
  { code: 'LHR', name: 'London Heathrow Airport', city: 'London' },
  { code: 'CDG', name: 'Charles de Gaulle Airport', city: 'Paris' },
  { code: 'NRT', name: 'Narita International Airport', city: 'Tokyo' },
  { code: 'DXB', name: 'Dubai International Airport', city: 'Dubai' },
  { code: 'SIN', name: 'Singapore Changi Airport', city: 'Singapore' },
  { code: 'HKG', name: 'Hong Kong International Airport', city: 'Hong Kong' },
  { code: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt' },
  { code: 'MAD', name: 'Madrid-Barajas Airport', city: 'Madrid' },
  { code: 'BCN', name: 'Barcelona-El Prat Airport', city: 'Barcelona' },
  { code: 'FCO', name: 'Leonardo da Vinci Airport', city: 'Rome' },
  { code: 'MXP', name: 'Malpensa Airport', city: 'Milan' },
  { code: 'AMS', name: 'Amsterdam Airport Schiphol', city: 'Amsterdam' },
  { code: 'ZUR', name: 'Zurich Airport', city: 'Zurich' },
  { code: 'VIE', name: 'Vienna International Airport', city: 'Vienna' },
  { code: 'MUC', name: 'Munich Airport', city: 'Munich' },
  { code: 'DUB', name: 'Dublin Airport', city: 'Dublin' },
  { code: 'LIS', name: 'Lisbon Airport', city: 'Lisbon' },
  { code: 'CPH', name: 'Copenhagen Airport', city: 'Copenhagen' },
  { code: 'ARN', name: 'Stockholm Arlanda Airport', city: 'Stockholm' },
  { code: 'OSL', name: 'Oslo Airport', city: 'Oslo' },
  { code: 'HEL', name: 'Helsinki Airport', city: 'Helsinki' },
  { code: 'WAW', name: 'Warsaw Chopin Airport', city: 'Warsaw' },
  { code: 'PRG', name: 'Václav Havel Airport', city: 'Prague' },
  { code: 'BUD', name: 'Budapest Ferenc Liszt Airport', city: 'Budapest' },
  { code: 'IST', name: 'Istanbul Airport', city: 'Istanbul' },
  { code: 'CAI', name: 'Cairo International Airport', city: 'Cairo' },
  { code: 'JNB', name: 'O.R. Tambo International Airport', city: 'Johannesburg' },
  { code: 'NBO', name: 'Jomo Kenyatta International Airport', city: 'Nairobi' },
  { code: 'BOM', name: 'Chhatrapati Shivaji Maharaj International Airport', city: 'Mumbai' },
  { code: 'DEL', name: 'Indira Gandhi International Airport', city: 'Delhi' },
  { code: 'BKK', name: 'Suvarnabhumi Airport', city: 'Bangkok' },
  { code: 'KUL', name: 'Kuala Lumpur International Airport', city: 'Kuala Lumpur' },
  { code: 'MNL', name: 'Ninoy Aquino International Airport', city: 'Manila' },
  { code: 'CGK', name: 'Soekarno-Hatta International Airport', city: 'Jakarta' },
  { code: 'SYD', name: 'Sydney Kingsford Smith Airport', city: 'Sydney' },
  { code: 'MEL', name: 'Melbourne Airport', city: 'Melbourne' },
  { code: 'YVR', name: 'Vancouver International Airport', city: 'Vancouver' },
  { code: 'YYZ', name: 'Toronto Pearson International Airport', city: 'Toronto' },
  { code: 'YUL', name: 'Montreal-Pierre Elliott Trudeau Airport', city: 'Montreal' },
  { code: 'GRU', name: 'São Paulo-Guarulhos International Airport', city: 'São Paulo' },
  { code: 'EZE', name: 'Ministro Pistarini International Airport', city: 'Buenos Aires' },
  { code: 'SCL', name: 'Arturo Merino Benítez International Airport', city: 'Santiago' },
  { code: 'LIM', name: 'Jorge Chávez International Airport', city: 'Lima' },
  { code: 'BOG', name: 'El Dorado International Airport', city: 'Bogotá' },
  { code: 'MEX', name: 'Mexico City International Airport', city: 'Mexico City' },
  { code: 'CUN', name: 'Cancún International Airport', city: 'Cancún' }
];

export const AIRLINES: Airline[] = [
  { code: 'AA', name: 'American Airlines' },
  { code: 'DL', name: 'Delta Air Lines' },
  { code: 'UA', name: 'United Airlines' },
  { code: 'WN', name: 'Southwest Airlines' },
  { code: 'BA', name: 'British Airways' },
  { code: 'AF', name: 'Air France' },
  { code: 'LH', name: 'Lufthansa' },
  { code: 'KL', name: 'KLM Royal Dutch Airlines' },
  { code: 'IB', name: 'Iberia' },
  { code: 'SN', name: 'Brussels Airlines' },
  { code: 'OS', name: 'Austrian Airlines' },
  { code: 'LX', name: 'Swiss International Air Lines' },
  { code: 'SK', name: 'SAS Scandinavian Airlines' },
  { code: 'AY', name: 'Finnair' },
  { code: 'LO', name: 'LOT Polish Airlines' },
  { code: 'OK', name: 'Czech Airlines' },
  { code: 'TK', name: 'Turkish Airlines' },
  { code: 'MS', name: 'EgyptAir' },
  { code: 'SA', name: 'South African Airways' },
  { code: 'KQ', name: 'Kenya Airways' },
  { code: 'AI', name: 'Air India' },
  { code: 'SG', name: 'SpiceJet' },
  { code: '6E', name: 'IndiGo' },
  { code: 'TG', name: 'Thai Airways' },
  { code: 'MH', name: 'Malaysia Airlines' },
  { code: 'PR', name: 'Philippine Airlines' },
  { code: 'GA', name: 'Garuda Indonesia' },
  { code: 'QF', name: 'Qantas' },
  { code: 'AC', name: 'Air Canada' },
  { code: 'WS', name: 'WestJet' },
  { code: 'JJ', name: 'LATAM Brasil' },
  { code: 'AR', name: 'Aerolíneas Argentinas' },
  { code: 'LA', name: 'LATAM Chile' },
  { code: 'AV', name: 'Avianca' },
  { code: 'AM', name: 'Aeroméxico' },
  { code: 'VW', name: 'Aeromar' },
  { code: 'EK', name: 'Emirates' },
  { code: 'QR', name: 'Qatar Airways' },
  { code: 'EY', name: 'Etihad Airways' },
  { code: 'SV', name: 'Saudia' },
  { code: 'GF', name: 'Gulf Air' },
  { code: 'KU', name: 'Kuwait Airways' },
  { code: 'RJ', name: 'Royal Jordanian' },
  { code: 'ME', name: 'Middle East Airlines' },
  { code: 'ET', name: 'Ethiopian Airlines' }
];

// Note: API configuration is now in environment files for security
