export interface Airport {
  code: string;
  name: string;
  city: string;
  state: string;
}

export interface Airline {
  code: string;
  name: string;
}

// Major US Airports
export const US_AIRPORTS: Airport[] = [
  // Major Hubs
  { code: 'ATL', name: 'Hartsfield-Jackson Atlanta International Airport', city: 'Atlanta', state: 'GA' },
  { code: 'LAX', name: 'Los Angeles International Airport', city: 'Los Angeles', state: 'CA' },
  { code: 'ORD', name: 'O\'Hare International Airport', city: 'Chicago', state: 'IL' },
  { code: 'DFW', name: 'Dallas/Fort Worth International Airport', city: 'Dallas', state: 'TX' },
  { code: 'DEN', name: 'Denver International Airport', city: 'Denver', state: 'CO' },
  { code: 'JFK', name: 'John F. Kennedy International Airport', city: 'New York', state: 'NY' },
  { code: 'SFO', name: 'San Francisco International Airport', city: 'San Francisco', state: 'CA' },
  { code: 'SEA', name: 'Seattle-Tacoma International Airport', city: 'Seattle', state: 'WA' },
  { code: 'LAS', name: 'McCarran International Airport', city: 'Las Vegas', state: 'NV' },
  { code: 'MIA', name: 'Miami International Airport', city: 'Miami', state: 'FL' },
  { code: 'CLT', name: 'Charlotte Douglas International Airport', city: 'Charlotte', state: 'NC' },
  { code: 'PHX', name: 'Phoenix Sky Harbor International Airport', city: 'Phoenix', state: 'AZ' },
  { code: 'EWR', name: 'Newark Liberty International Airport', city: 'Newark', state: 'NJ' },
  { code: 'MCO', name: 'Orlando International Airport', city: 'Orlando', state: 'FL' },
  { code: 'IAH', name: 'George Bush Intercontinental Airport', city: 'Houston', state: 'TX' },
  { code: 'MSP', name: 'Minneapolis-Saint Paul International Airport', city: 'Minneapolis', state: 'MN' },
  { code: 'DTW', name: 'Detroit Metropolitan Wayne County Airport', city: 'Detroit', state: 'MI' },
  { code: 'PHL', name: 'Philadelphia International Airport', city: 'Philadelphia', state: 'PA' },
  { code: 'LGA', name: 'LaGuardia Airport', city: 'New York', state: 'NY' },
  { code: 'BWI', name: 'Baltimore/Washington International Thurgood Marshall Airport', city: 'Baltimore', state: 'MD' },
  { code: 'SLC', name: 'Salt Lake City International Airport', city: 'Salt Lake City', state: 'UT' },
  { code: 'DCA', name: 'Ronald Reagan Washington National Airport', city: 'Washington', state: 'DC' },
  { code: 'MDW', name: 'Chicago Midway International Airport', city: 'Chicago', state: 'IL' },
  { code: 'HNL', name: 'Daniel K. Inouye International Airport', city: 'Honolulu', state: 'HI' },
  { code: 'BOS', name: 'Logan International Airport', city: 'Boston', state: 'MA' },
  { code: 'FLL', name: 'Fort Lauderdale-Hollywood International Airport', city: 'Fort Lauderdale', state: 'FL' },
  { code: 'IAD', name: 'Washington Dulles International Airport', city: 'Washington', state: 'DC' },
  { code: 'SAN', name: 'San Diego International Airport', city: 'San Diego', state: 'CA' },
  { code: 'TPA', name: 'Tampa International Airport', city: 'Tampa', state: 'FL' },
  { code: 'PDX', name: 'Portland International Airport', city: 'Portland', state: 'OR' },
  { code: 'STL', name: 'St. Louis Lambert International Airport', city: 'St. Louis', state: 'MO' },
  { code: 'HOU', name: 'William P. Hobby Airport', city: 'Houston', state: 'TX' },
  { code: 'AUS', name: 'Austin-Bergstrom International Airport', city: 'Austin', state: 'TX' },
  { code: 'BNA', name: 'Nashville International Airport', city: 'Nashville', state: 'TN' },
  { code: 'MCI', name: 'Kansas City International Airport', city: 'Kansas City', state: 'MO' },
  { code: 'CLE', name: 'Cleveland Hopkins International Airport', city: 'Cleveland', state: 'OH' },
  { code: 'PIT', name: 'Pittsburgh International Airport', city: 'Pittsburgh', state: 'PA' },
  { code: 'RDU', name: 'Raleigh-Durham International Airport', city: 'Raleigh', state: 'NC' },
  { code: 'IND', name: 'Indianapolis International Airport', city: 'Indianapolis', state: 'IN' },
  { code: 'CMH', name: 'John Glenn Columbus International Airport', city: 'Columbus', state: 'OH' },
  { code: 'CVG', name: 'Cincinnati/Northern Kentucky International Airport', city: 'Cincinnati', state: 'OH' },
  { code: 'MKE', name: 'Milwaukee Mitchell International Airport', city: 'Milwaukee', state: 'WI' },
  { code: 'MSY', name: 'Louis Armstrong New Orleans International Airport', city: 'New Orleans', state: 'LA' },
  { code: 'SJC', name: 'Norman Y. Mineta San José International Airport', city: 'San Jose', state: 'CA' },
  { code: 'OAK', name: 'Oakland International Airport', city: 'Oakland', state: 'CA' },
  { code: 'SNA', name: 'John Wayne Airport', city: 'Santa Ana', state: 'CA' },
  { code: 'BUR', name: 'Hollywood Burbank Airport', city: 'Burbank', state: 'CA' },
  { code: 'ONT', name: 'Ontario International Airport', city: 'Ontario', state: 'CA' },
  { code: 'SMF', name: 'Sacramento International Airport', city: 'Sacramento', state: 'CA' },
  { code: 'ABQ', name: 'Albuquerque International Sunport', city: 'Albuquerque', state: 'NM' },
  { code: 'TUS', name: 'Tucson International Airport', city: 'Tucson', state: 'AZ' },
  { code: 'ELP', name: 'El Paso International Airport', city: 'El Paso', state: 'TX' },
  { code: 'SAT', name: 'San Antonio International Airport', city: 'San Antonio', state: 'TX' },
  { code: 'OKC', name: 'Will Rogers World Airport', city: 'Oklahoma City', state: 'OK' },
  { code: 'TUL', name: 'Tulsa International Airport', city: 'Tulsa', state: 'OK' },
  { code: 'LIT', name: 'Clinton National Airport', city: 'Little Rock', state: 'AR' },
  { code: 'MEM', name: 'Memphis International Airport', city: 'Memphis', state: 'TN' },
  { code: 'BHM', name: 'Birmingham-Shuttlesworth International Airport', city: 'Birmingham', state: 'AL' },
  { code: 'MOB', name: 'Mobile Regional Airport', city: 'Mobile', state: 'AL' },
  { code: 'JAX', name: 'Jacksonville International Airport', city: 'Jacksonville', state: 'FL' },
  { code: 'RSW', name: 'Southwest Florida International Airport', city: 'Fort Myers', state: 'FL' },
  { code: 'PBI', name: 'Palm Beach International Airport', city: 'West Palm Beach', state: 'FL' },
  { code: 'SAV', name: 'Savannah/Hilton Head International Airport', city: 'Savannah', state: 'GA' },
  { code: 'CHS', name: 'Charleston International Airport', city: 'Charleston', state: 'SC' },
  { code: 'GSP', name: 'Greenville-Spartanburg International Airport', city: 'Greenville', state: 'SC' },
  { code: 'RNO', name: 'Reno-Tahoe International Airport', city: 'Reno', state: 'NV' },
  { code: 'BOI', name: 'Boise Airport', city: 'Boise', state: 'ID' },
  { code: 'SLC', name: 'Salt Lake City International Airport', city: 'Salt Lake City', state: 'UT' },
  { code: 'COS', name: 'Colorado Springs Airport', city: 'Colorado Springs', state: 'CO' },
  { code: 'OMA', name: 'Eppley Airfield', city: 'Omaha', state: 'NE' },
  { code: 'DSM', name: 'Des Moines International Airport', city: 'Des Moines', state: 'IA' },
  { code: 'MSP', name: 'Minneapolis-Saint Paul International Airport', city: 'Minneapolis', state: 'MN' },
  { code: 'FAR', name: 'Hector International Airport', city: 'Fargo', state: 'ND' },
  { code: 'BIL', name: 'Billings Logan International Airport', city: 'Billings', state: 'MT' },
  { code: 'BOZ', name: 'Bozeman Yellowstone International Airport', city: 'Bozeman', state: 'MT' },
  { code: 'SEA', name: 'Seattle-Tacoma International Airport', city: 'Seattle', state: 'WA' },
  { code: 'GEG', name: 'Spokane International Airport', city: 'Spokane', state: 'WA' },
  { code: 'PDX', name: 'Portland International Airport', city: 'Portland', state: 'OR' },
  { code: 'EUG', name: 'Eugene Airport', city: 'Eugene', state: 'OR' },
  { code: 'SFO', name: 'San Francisco International Airport', city: 'San Francisco', state: 'CA' },
  { code: 'LAX', name: 'Los Angeles International Airport', city: 'Los Angeles', state: 'CA' },
  { code: 'SAN', name: 'San Diego International Airport', city: 'San Diego', state: 'CA' },
  { code: 'SJC', name: 'Norman Y. Mineta San José International Airport', city: 'San Jose', state: 'CA' },
  { code: 'OAK', name: 'Oakland International Airport', city: 'Oakland', state: 'CA' },
  { code: 'SNA', name: 'John Wayne Airport', city: 'Santa Ana', state: 'CA' },
  { code: 'BUR', name: 'Hollywood Burbank Airport', city: 'Burbank', state: 'CA' },
  { code: 'ONT', name: 'Ontario International Airport', city: 'Ontario', state: 'CA' },
  { code: 'SMF', name: 'Sacramento International Airport', city: 'Sacramento', state: 'CA' },
  { code: 'HNL', name: 'Daniel K. Inouye International Airport', city: 'Honolulu', state: 'HI' },
  { code: 'OGG', name: 'Kahului Airport', city: 'Kahului', state: 'HI' },
  { code: 'KOA', name: 'Kona International Airport', city: 'Kailua-Kona', state: 'HI' },
  { code: 'LIH', name: 'Lihue Airport', city: 'Lihue', state: 'HI' },
  { code: 'ANC', name: 'Ted Stevens Anchorage International Airport', city: 'Anchorage', state: 'AK' },
  { code: 'FAI', name: 'Fairbanks International Airport', city: 'Fairbanks', state: 'AK' },
  { code: 'JNU', name: 'Juneau International Airport', city: 'Juneau', state: 'AK' }
];

// Major US Airlines
export const US_AIRLINES: Airline[] = [
  { code: 'AA', name: 'American Airlines' },
  { code: 'DL', name: 'Delta Air Lines' },
  { code: 'UA', name: 'United Airlines' },
  { code: 'WN', name: 'Southwest Airlines' },
  { code: 'B6', name: 'JetBlue Airways' },
  { code: 'NK', name: 'Spirit Airlines' },
  { code: 'F9', name: 'Frontier Airlines' },
  { code: 'AS', name: 'Alaska Airlines' },
  { code: 'HA', name: 'Hawaiian Airlines' },
  { code: 'G4', name: 'Allegiant Air' },
  { code: 'SY', name: 'Sun Country Airlines' },
  { code: 'YX', name: 'Republic Airways' },
  { code: 'MQ', name: 'Envoy Air' },
  { code: 'OH', name: 'PSA Airlines' },
  { code: 'PT', name: 'Piedmont Airlines' },
  { code: '9E', name: 'Endeavor Air' },
  { code: 'CP', name: 'Compass Airlines' },
  { code: 'OO', name: 'SkyWest Airlines' },
  { code: 'QX', name: 'Horizon Air' },
  { code: 'VX', name: 'Virgin America' },
  { code: 'F9', name: 'Frontier Airlines' },
  { code: 'NK', name: 'Spirit Airlines' },
  { code: 'B6', name: 'JetBlue Airways' },
  { code: 'WN', name: 'Southwest Airlines' },
  { code: 'AS', name: 'Alaska Airlines' },
  { code: 'HA', name: 'Hawaiian Airlines' },
  { code: 'G4', name: 'Allegiant Air' },
  { code: 'SY', name: 'Sun Country Airlines' },
  { code: 'YX', name: 'Republic Airways' },
  { code: 'MQ', name: 'Envoy Air' },
  { code: 'OH', name: 'PSA Airlines' },
  { code: 'PT', name: 'Piedmont Airlines' },
  { code: '9E', name: 'Endeavor Air' },
  { code: 'CP', name: 'Compass Airlines' },
  { code: 'OO', name: 'SkyWest Airlines' },
  { code: 'QX', name: 'Horizon Air' },
  { code: 'VX', name: 'Virgin America' }
];
